### PR TITLE
Switch Sparkpost to using current crypto system

### PR DESCRIPTION
**Pull request by seamuslee001**

### CODE REVIEW

**Comment by nganivet** [comment]
Actually @seamuslee001 , I have lost interest in maintaining this extension since now using another provider. Would you be willing to co-maintain this extension if it is transferred to lab.civicrm.org?

**Comment by herbdool** [comment]
Maybe it's a good time to merge this project with https://lab.civicrm.org/extensions/sparkpost and add any upgrade paths? @mlutfy

**Comment by nganivet** [comment]
@herbdool Thanks for the patch and sorry I merged this pull request without verifying based on the reputation of the authors.

**Comment by nganivet** [comment]
@herbdool On a side note, it would have been more polite to ask me before suggesting to move to lab.civicrm.org ...

**Comment by herbdool** [comment]
@nganivet you said: "Would you be willing to co-maintain this extension if it is transferred to lab.civicrm.org". So I replied with asking if it would be a good time to merge it with the other project. I don't see how this is impolite.

You seem to want to get it off your hands so I reached out to see who might be interested.

**Comment by nganivet** [comment]
Sorry about the wrong choice of words, but at least let's agree that we need one or two co-maintainers before talking about any transfer of ownership. It would serve no purpose to move the repository absent this condition, hence my opposition.

**Comment by mlutfy** [comment]
@herbdool We are maintaining our fork (https://civicrm.org/extensions/sparkpost-symbiotic) and if there is something to do in order to help with switching, patches welcome. Since our fork uses a different extension key (Sparkpost instead of the old long-form), it's not a drop-in replacement - the old extension has to be disabled/uninstalled, then enable/configure the new one.

If this extension is no longer maintained, I will removed the "available for in-app install" status on civicrm.org.

**Pull request merged**
