### PR TITLE
Add ability to use EU-hosted platform

### PR DESCRIPTION
**Pull request by herbdool**
Addresses https://github.com/cividesk/com.cividesk.email.sparkpost/issues/69

### CODE REVIEW

**Comment by nganivet** [comment]
@herbdool Good, the PR looks better now. Can you change from a Yes/No to a Select drop-down for the endpoint? Thanks.

**Comment by herbdool** [comment]
@nganivet I think it's better now. I've tested with both platforms and seems fine to me.

**Comment by karex** [comment]
Is there an ETA for this merge? Would be really good to use this extension with the EU service of SparkPost. Is there anything one can do to make this happen?

**Comment by herbdool** [comment]
@karex it would probably help to test this PR and then report back.

**Comment by nganivet** [comment]
@herbdool sorry this got to the bottom of the pile
@karex merged, please test and tell us if it works for you

**Comment by karex** [comment]
@herbdool @nganivet I've tested it and it works: sends the mails, installs the webhook, handles bounces. Thanks!

**Pull request merged**
